apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-counter-deployment
spec:
  replicas: 1  # You can scale to more replicas if needed
  selector:
    matchLabels:
      app: fastapi-counter-app
  template:
    metadata:
      labels:
        app: fastapi-counter-app
    spec:
      containers:
        - name: fastapi-counter
          image: naseevadk/fastapi-counter-app:f46ca16f3da45cd872dcec0ddb458a37f709e313  # Your Docker Hub image
          ports:
            - containerPort: 80  # Port where FastAPI is running inside the container
