apiVersion: v1
kind: Service
metadata:
  name: fastapi-counter-service
spec:
  selector:
    app: fastapi-counter-app  # Match the label in the deployment
  ports:
    - protocol: TCP
      port: 80         # Port exposed inside the Kubernetes cluster
      targetPort: 80  # Port inside the container where FastAPI app is running
      nodePort: 30001   # Port on your Minikube VM that you can access externally
  type: NodePort
