name: CI/CD for FastAPI Counter App

on:
  push:
    paths:
      - "app/main.py"  # Trigger only if changes are made to main.py

jobs:
  lint:
    name: Lint Python Code with Pylint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run Pylint
        run: |
          pylint app/main.py
        # The job will fail here if pylint errors are found

  docker:
    name: Build and Push Docker Image
    needs: lint  # Run this job only if the 'lint' job succeeds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t naseevadk/fastapi-counter-app:${{ github.sha }} .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push naseevadk/fastapi-counter-app:${{ github.sha }}
